# Generated by Django 5.2.17 on 2026-08-26 05:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('resource_type', models.CharField(choices=[('COURT', 'Court'), ('MEETING_ROOM', 'Meeting room'), ('STUDIO', 'Studio')], default='COURT', max_length=32)),
                ('surface', models.CharField(blank=True, choices=[('CLAY', 'Tierra batida'), ('GRASS', 'Hierba'), ('HARD', 'Dura')], max_length=16, null=True)),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('image_url', models.URLField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending')], default='CONFIRMED', max_length=16)),
                ('recurrence_group_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.resource')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['resource', 'start_time', 'end_time', 'status'], name='booking_resource_range_status')],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='booking_start_before_end')],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.PositiveSmallIntegerField(help_text='0=Monday ... 6=Sunday')),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('slot_duration_minutes', models.PositiveIntegerField(default=60)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='bookings.resource')),
            ],
            options={
                'verbose_name_plural': 'availabilities',
                'ordering': ['resource', 'day_of_week', 'open_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(('open_time__lt', models.F('close_time'))), name='availability_open_before_close'), models.CheckConstraint(condition=models.Q(('day_of_week__gte', 0), ('day_of_week__lte', 6)), name='availability_valid_weekday')],
            },
        ),
    ]
